### ISSUE TITLE
Very interesting - have you found any way to control the solar settings?

### ISSUE THREAD

**Issue by RobHayden** [strobejb/andersen-ev#5]
I've had an outstanding request with Andersen for a long time to have them add the solar setting to their schedule configuration so that it doesn't try to charge at 100% solar during the night.

Running a time-of-day based script to flip this setting in the morning and evening would achieve the same objective but I don't know if it's available via the API.

**Comment by strobejb** [comment]
Hi,
I don't have my A2 configured with Solar, so I haven't spent much attention to the solar parts of the API. Can you clarify what you are trying to do? (I'm not sure what you mean by 'charge 100% solar during the night').

The latest A2 API seems to suggest that there are more options for controlling charging rates (i.e setting min & max charge rate). Here are some GraphQL DeviceStatus variables that haven't been exposed by the python library (yet):

* solarMaxGridChargePercent
* solarChargeAlways
* solarOverride
* cfgChargeAmpMax
* cfgAFAmpMax

So I think there are some features coming to the Konnect+ (maybe soon) that will allow more control of the unit

**Comment by RobHayden** [comment]
Thanks for the reply.

There are two settings for solar, which only appear on the app if you have your Konnect+ account enabled for solar;
(1) The grid vs excess solar excess incoming power balance that should be used for charging which has 5 settings 100/75/50/25/0 from full grid to full solar.
(2) A toggle whether the charger should supply a minimum of 1.4kW no matter how much solar excess is available.

During the day, you would typically have a schedule set to e.g. 0830 to 1730 to charge while the sun is shining and set (1) to 0% grid but leave (2) on Yes so that if it clouds over, then the charger will continue to charge drawing a little power from the house battery (or grid) just to keep charging ticking over.

Most people then typically have a "low cost" schedule set for some time during the night of course.

If you forget to change (1) away from max solar (0% grid) then when that schedule kicks in at night, you only get 1.4kW if you had (2) set to Yes. I'm not actually sure what happens if you have (2) set to No. Possibly no charging at all.

And the reverse is also true - if you forget to change from 100% grid first thing in the morning, and the car still isn't fully charged but is still plugged in, then at 0830 you are suddenly pulling 7kW at expensive prices from the grid.

I've done both of these more often than I care to admit. Sometimes the first scenario resulting in a major domestic incident when my wife's car hasn't got enough SOC for what she's got planned that day. So what I want to do is set up 2 chron jobs / scheduled tasks every day running scripts which at 8am sets it to 100% solar and at 11pm sets it to 100% grid.

**Comment by strobejb** [comment]
ok, so at the moment there haven't been any changes in the Andersen API that will let you configure solar settings for each schedule. But there is an existing API that I think can be used to set the solar charge rate:

(line 246)
 `def set_solar(self, deviceId, override=False, chargeAlways=False, maxGridChargePercent=10)`

that one probably does what you need it to do - call it like this:

`a2.set_solar(deviceId, maxGridChargePercent=50)`

I need to get my solar hooked up to the A2 so I can properly test this

**Comment by RobHayden** [comment]
Thanks, going to give it a try! I am properly rusty with python dev so you won't want to see a PR from me but I'll post my results in here.

**Comment by RobHayden** [comment]
That works nicely, thanks!
Just need to find an elegant place to run it twice a day without leaving my PC on 24 hours.
The call doesn't seem to return anything, is that right? I guess you use get_solar afterwards if you want to check it worked.
Also, I had to use chargeAlways=True to make it turn on the option to sip from the grid if the excess available solar was below 1.4kW
